/**
 * Exports the civilization pieces from the mockup into the game.
 *
 *   NODE_PATH=<dir with playwright>/node_modules node scripts/export_civ_pieces.js
 *
 * public/mockups/civ-pieces.html is where the pieces are designed: it draws every civilization in
 * its browser script. This opens it headless, takes the roster (its READY list) with the designs
 * picked in its CHOICES, and writes:
 *   - public/images/pieces/civ/<civ>-settlement.svg and <civ>-city.svg
 *   - public/css/civ-pieces.css, the --civ-settlement / --civ-city of every [data-civ]
 * It fails when the roster no longer matches CONST.CIVS, which the server picks from.
 *
 * Playwright is not a dependency of the game: install it anywhere and point NODE_PATH at it.
 */
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { CIVS } from '../public/js/const.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const MOCKUP = path.join(ROOT, 'public/mockups/civ-pieces.html')
const OUT = path.join(ROOT, 'public/images/pieces/civ')
const CSS = path.join(ROOT, 'public/css/civ-pieces.css')

let chromium
try { ({ chromium } = createRequire(import.meta.url)('playwright')) } catch (e) {
  console.error('Playwright not found. Install it outside the repo and run with NODE_PATH=<that>/node_modules.')
  process.exit(1)
}

const browser = await chromium.launch()
const page = await browser.newPage()
const errors = []
page.on('pageerror', e => errors.push(e.message))
await page.goto(pathToFileURL(MOCKUP).href)
const roster = await page.evaluate(() => READY.map(slug => ({ slug, S: eff(slug, 'S').svg, C: eff(slug, 'C').svg })))
await browser.close()
if (errors.length) { console.error('The mockup threw:', errors); process.exit(1) }

const slugs = roster.map(r => r.slug)
if (slugs.join() !== CIVS.join()) {
  console.error(`The mockup's READY list and CONST.CIVS differ:\n  READY: ${slugs.join(', ')}\n  CIVS:  ${CIVS.join(', ')}`)
  process.exit(1)
}

fs.mkdirSync(OUT, { recursive: true })
for (const f of fs.readdirSync(OUT)) if (f.endsWith('.svg')) fs.rmSync(path.join(OUT, f))
const url = (slug, kind) => `/images/pieces/civ/${slug}-${kind}.svg`
for (const { slug, S, C } of roster) {
  fs.writeFileSync(path.join(OUT, `${slug}-settlement.svg`), S + '\n')
  fs.writeFileSync(path.join(OUT, `${slug}-city.svg`), C + '\n')
}
fs.writeFileSync(CSS, `/*
 * Generated by scripts/export_civ_pieces.js from public/mockups/civ-pieces.html: do not edit here.
 * Each civilization's pieces as --civ-settlement / --civ-city on whatever carries its data-civ.
 * constants.css turns them into --piece-settlement / --piece-city where civ pieces are on.
 */
${roster.map(({ slug }) => `[data-civ="${slug}"] { --civ-settlement: url(${url(slug, 'settlement')}); --civ-city: url(${url(slug, 'city')}); }`).join('\n')}
`)
console.log(`${roster.length} civilizations: ${slugs.join(', ')}`)
